system("ruby", "1.Resize_Hacks.rb")
system("ruby", "2.ASM-Hacks.rb")
system("ruby", "3.Parse-GFX.rb")
system("ruby", "4.Parse-Text.rb")
system("ruby", "5.Parse-Menus.rb")
system("ruby", "6.Parse-Table.rb")
system("ruby", "7.Parse-UI.rb")