system("ruby", "1.Initial-Hacks.rb")
system("ruby", "2.ASM-Hacks.rb")
system("ruby", "3.Parse-Dialogues.rb")
system("ruby", "4.Parse-PTRTables.rb")
system("ruby", "5.Parse-Menus.rb")
system("ruby", "6.Parse-CodePointers.rb")
system("ruby", "7.Parse-Items.rb")
system("ruby", "8.Parse-Cutscenes.rb")
